import SignUpForm from "@/components/SignUpForm";
import { Metadata } from "next";
import Link from "next/link";
import headerLogo from "../../../public/images/headerLogo.svg";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Signup - jober AI",
  description: "Generated by create next app",
};

const SignUpPage = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-[90vh] bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full">
        <div className="text-center mb-6">
          <div className="flex justify-center">
            <Image priority src={headerLogo} alt="Follow us on Twitter" />
          </div>
          <h2 className="text-2xl font-semibold mt-4">Create your account</h2>
        </div>
        <SignUpForm />

        <div className="text-center mt-4">
          <p className="text-sm text-gray-600">
            Have an account ?
            <Link href="/login" className="text-primary-light">
              {" "}
              Login
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default SignUpPage;
